version: 0.2

env:
  variables:
    GO111MODULE: "on"

phases:
  pre_build:
    commands:
      - make deps
  build:
    commands:
      - echo Build started on `date`
      - make
      - make build
  post_build:
    commands:
      - echo Build finished on `date`